# Generated by Django 5.0 on 2024-02-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_rename_members_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
