# Generated by Django 5.0 on 2024-02-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_rename_first_name_member_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
